### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Dorodororo** [GenesicZyrael/CrimsonAlpha#1]
not a issue but really the only way i can say, super good job for sure the best custom card creator on here keep on keeping on

**Comment by GenesicZyrael** [comment]
> not a issue but really the only way i can say, super good job for sure the best custom card creator on here keep on keeping on

Aww... Thanks for the kind words. I appreciate it. 😊

**Comment by Dorodororo** [comment]
no problem just keep on keeping on
(also make a lswarm xyz  boss monster)

**Comment by GenesicZyrael** [comment]
I'll see what I can do
